---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 3 # Creates 3 separate pods for load balancing
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami-container
          image: traefik/whoami:latest
          ports:
            - containerPort: 80 # The port the container listens on internally
