---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  type: ClusterIP # Keeps the service strictly internal to the cluster
  selector:
    app: whoami # This must match the label in your deployment!
  ports:
    - port: 80 # The port the service listens on
      targetPort: 80 # The port it sends traffic to on the container
